/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  1660990954: {
    HelloStatusNetwork: {
      address: "0x9d689A794eF2877827938C9D740b17Fd5E6f2a25",
      abi: [
        {
          inputs: [],
          name: "getGreet",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [],
          name: "greet",
          outputs: [
            {
              internalType: "string",
              name: "",
              type: "string",
            },
          ],
          stateMutability: "view",
          type: "function",
        },
        {
          inputs: [
            {
              internalType: "string",
              name: "_greet",
              type: "string",
            },
          ],
          name: "setGreet",
          outputs: [],
          stateMutability: "nonpayable",
          type: "function",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 11741830,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
